### ISSUE TITLE
Pull in NitroAdjudicator bytecode from npm (when v2  is published there)

### ISSUE THREAD

**Issue by geoknee** [statechannels/hardhat-docker#3]
I think this will be solved when we pull in the build artifacts from npm. The version will be specified in the `package.json` of this repo.

_Originally posted by @geoknee in https://github.com/statechannels/hardhat-docker/pull/2#discussion_r969482014_

**Comment by kerzhner** [comment]
Nitro contracts are no longer deployed on Docker start. See https://github.com/statechannels/go-nitro-testground/pull/121.
